[project]
name = "asgiref"
dynamic = ["version"]
authors = [
  { name = "Django Software Foundation", email = "foundation@djangoproject.com" },
]
description = "ASGI specs, helper code, and adapters"
readme = "README.rst"
license = "BSD-3-Clause"

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Web Environment",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15",
  "Programming Language :: Python :: Free Threading :: 2 - Beta",
  "Topic :: Internet :: WWW/HTTP",
]
requires-python = ">=3.11"

[project.urls]
Homepage = "https://github.com/django/asgiref/"
Documentation = "https://asgi.readthedocs.io/"
"Further Documentation" = "https://docs.djangoproject.com/en/stable/topics/async/#async-adapter-functions"
Changelog = "https://github.com/django/asgiref/blob/master/CHANGELOG.txt"


[project.optional-dependencies]
tests = [
  "pytest",
  "pytest-asyncio",
]

mypy = [
  "mypy>=1.14.0",
]


[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages]
find = {}

[tool.setuptools.dynamic]
version = { attr = "asgiref.__version__" }

